config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  resources   :users,              only: [:index] # ユーザー登録は管理者側から行うため、ユーザー側にはユーザー一覧の取得機能しかついてない
  resources   :subjects,           only: [:index, :new, :create, :show, :destroy] do
    resources :teaching_materials, only: [:new, :create, :destroy, :edit, :update]
    resources :exams,              only: [:new, :create, :destroy, :edit, :update]
    resources :questions,          only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_many_attached :files
  
  validates :title, presence: true
  validates :files, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  
  validates :question, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :subject_users, dependent: :destroy
  has_many :users, through: :subject_users
  has_many :teaching_materials, dependent: :destroy
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_one_attached :image

  validates :subject_name, presence: true
  validates :image, presence: true
end

app/models/subject_user.rb
class SubjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :subject
end

app/models/teaching_material.rb
class TeachingMaterial < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_many_attached :files
  
  validates :title, presence: true
  validates :files, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :subject_users
  has_many :subjects, through: :subject_users
  has_many :teaching_materials
  has_many :exams
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  # 各アクションの実行前に実行される
  # ログインしていないユーザーをTopページに遷移させる
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @subject = Subject.find(params[:subject_id])
    @exam = Exam.new
    unless @subject.user_id == current_user.id
      redirect_to root_path
    end
  end

  def create
    @exam = Exam.new(exam_params)
    @exam.user_id = current_user.id
    if @exam.save
      redirect_to subject_path(@exam.subject)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @subject = Subject.find(params[:subject_id])
    @exams = @subject.exams
  end

  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy
    redirect_to subject_path(@exam.subject)
  end

  def edit
    @subject = Subject.find(params[:subject_id])
    @exam = Exam.find(params[:id])

    unless @exam.user_id == current_user.id
      redirect_to root_path
    end
  end

  def update
    @exam = Exam.find(params[:id])
    if @exam.update(exam_params)
      redirect_to subject_path(@exam.subject)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def exam_params
    params.require(:exam).permit(:title, files: []).merge(user_id: current_user.id, subject_id: params[:subject_id])
  end

  def authenticate_user!
    # ユーザーがログインしていない場合はリダイレクト
    redirect_to new_user_session_path unless current_user
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    @question.save
    redirect_to subject_path(@question.subject_id)
  end

  def destroy
    question = Question.find(params[:id])
    @subject = Subject.find(params[:subject_id])
    question.destroy
    redirect_to @subject
  end


  private

  def question_params
    params.require(:question).permit(:question).merge(user_id: current_user.id, subject_id: params[:subject_id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # 各アクションの実行前に実行される
  # ログインしていないユーザーをTopページに遷移させる
  before_action :authenticate_user!, only: [:new, :create, :show]

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    @subject.user_id = current_user.id

    if @subject.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @subject = Subject.find(params[:id])
    @user = User.find(@subject.user_id)
    @teaching_materials = @subject.teaching_materials
    @exams = @subject.exams
    @questions = @subject.questions.includes(:user)
    @question = @subject.questions.build(user: current_user)
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    redirect_to root_path
  end

  private

  def subject_params
    params.require(:subject).permit(:subject_name, :image).merge(user_ids: current_user.id)
  end

  def authenticate_user!
    # ユーザーがログインしていない場合はリダイレクト
    redirect_to new_user_session_path unless current_user
  end

end

app/controllers/teaching_materials_controller.rb
class TeachingMaterialsController < ApplicationController
  # 各アクションの実行前に実行される
  # ログインしていないユーザーをTopページに遷移させる
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_subject

  def new
    @subject = Subject.find(params[:subject_id])
    @teaching_material = TeachingMaterial.new

    unless @subject.user_id == current_user.id
      redirect_to root_path
    end
  end

  def create
    @teaching_material = TeachingMaterial.new(teaching_material_params)
    @teaching_material.user_id = current_user.id
    if @teaching_material.save
      redirect_to subject_path(@teaching_material.subject)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @subject = Subject.find(params[:subject_id])
    @teaching_materials = @subject.teaching_materials
  end

  def destroy
    @teaching_material = TeachingMaterial.find(params[:id])
    @teaching_material.destroy
    redirect_to subject_path(@teaching_material.subject)
  end

  def edit
    @subject = Subject.find(params[:subject_id])
    @teaching_material = TeachingMaterial.find(params[:id])

    unless @teaching_material.user_id == current_user.id
      redirect_to root_path
    end
  end

  def update
    @teaching_material = TeachingMaterial.find(params[:id])
    if @teaching_material.update(teaching_material_params)
      redirect_to subject_path(@teaching_material.subject)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def teaching_material_params
    params.require(:teaching_material).permit(:title, files: []).merge(user_id: current_user.id, subject_id: params[:subject_id])
  end

  def authenticate_user!
    # ユーザーがログインしていない場合はリダイレクト
    redirect_to new_user_session_path unless current_user
  end

  def set_subject
    @subject = Subject.find(params[:subject_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @subjects = Subject.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teaching_materials_helper.rb
module TeachingMaterialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exams/edit.html.erb
<div class="contents-new">
  <div class="container">
    <h3>編集する(問題)</h3>
    <%= form_with(model: [@subject, @exam], local: true) do |f| %>
      <%= f.text_field :title, placeholder: "タイトル" %>
      <%= f.file_field :files, multiple: true %>
      ※2つ目にPDFデータを選択してください
      <%= f.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/exams/new.html.erb
<div class="contents-new">
  <div class="container">
    <h3>問題投稿</h3>
    <%= form_with(model: [@subject, @exam], local: true) do |f| %>
      <%= f.text_field :title, placeholder: "タイトル" %>
      <%= f.file_field :files, multiple: true %>
      ※2つ目にPDFデータを選択してください
      <%= f.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agri40237</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">AGRI MASTER</a></h1>

        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span class="user_name"> <%= current_user.nickname %> </span>
            <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
            <%= link_to "科目登録", new_subject_path, class: "post" %>
          </div>
        <% else %>
          <div class="user_nav grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>

      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright AGRI MASTER 2024.
      </p>
    </footer>
  </body>
</html>

app/views/subjects/new.html.erb
<div class="contents-new">
  <div class="container">
    <h3>科目登録</h3>
    <%= form_with(model: @subject, local: true) do |f| %>
      <%= f.text_field :subject_name, placeholder: "科目名" %>
      <%= f.file_field :image %>
      <%= f.submit "登録" %>
    <% end %>
  </div>
</div>

app/views/subjects/show.html.erb
<div class="subject-info">
  <p>投稿者：<%= @user.nickname %></p>
</div>

<div class="posting">

  <div class="poston">
    
    <% if current_user.id == @subject.user_id %>
      <%= link_to "教材投稿", new_subject_teaching_material_path(@subject), class: "posti" %>
    <% else %>
      <span class="posta">教材一覧</span>
    <% end %>

    <div class="teaching_material_title">
      <% @teaching_materials.each_with_index do |teaching_material, index| %>
        <div class="exam-item">
          <%= "#{index + 1}. " %>
          <%= link_to teaching_material.title, rails_blob_url(teaching_material.files.first), target: "_blank" %>
          <% if teaching_material.files.second %>
            <%= link_to "(PDF)", rails_blob_url(teaching_material.files.second), target: "_blank" %>
          <% end %>
          <% if teaching_material.user_id == current_user.id %>
            <%= link_to "編集", edit_subject_teaching_material_path(@subject, teaching_material), class: "edit-button" %>
            <%= link_to "削除", subject_teaching_material_path(@subject, teaching_material), data: { turbo_method: :delete }, class: "delete-button", 'data-confirm': '本当に削除していいですか？' %>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <div class="poston">

    <% if current_user.id == @subject.user_id %>
      <%= link_to "問題投稿", new_subject_exam_path(@subject), class: "posti" %>
    <% else %>
      <span class="posta">問題一覧</span>
    <% end %>

    <div class="teaching_material_title">
      <% @exams.each_with_index do |exam, index| %>
        <div class="exam-item">
          <%= "#{index + 1}. " %>
          <%= link_to exam.title, rails_blob_url(exam.files.first), target: "_blank" %>
          <% if exam.files.second %>
            <%= link_to "(PDF)", rails_blob_url(exam.files.second), target: "_blank" %>
          <% end %>
          <% if exam.user_id == current_user.id %>
            <%= link_to "編集", edit_subject_exam_path(@subject, exam), class: "edit-button" %>
            <%= link_to "削除", subject_exam_path(@subject, exam), data: { turbo_method: :delete }, class: "delete-button", 'data-confirm': '本当に削除していいですか？' %>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

</div>

<%= form_with model: [@subject, @question], id: "question-form" do |f| %>
  <%= f.text_area :question, placeholder: "質問を入力", rows: "5", class: "question_form" %><br>
  <%= f.submit "質問する", class: "subject_question" %>
<% end %>

<div class="questions" id="questions">
  <h4>＜質問一覧＞</h4><br>
  <% @questions.each do |question| %>
    <p class="user-info">
      <%= question.user.nickname %>：<%= question.question %>
      <% if current_user == question.user %>
        <%= link_to '削除', subject_question_path(@subject, question), data: { turbo_method: :delete }, class: 'question-delete-link', 'data-confirm': '本当に削除していいですか？' %>
      <% end %>
    </p><br>
  <% end %>
</div>

app/views/teaching_materials/edit.html.erb
<div class="contents-new">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: [@subject, @teaching_material], local: true) do |f| %>
      <%= f.text_field :title, placeholder: "タイトル" %>
      <%= f.file_field :files, multiple: true %>
      ※2つ目にPDFデータを選択してください
      <%= f.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/teaching_materials/new.html.erb
<div class="contents-new">
  <div class="container">
    <h3>教材投稿</h3>
    <%= form_with(model: [@subject, @teaching_material], local: true) do |f| %>
      <%= f.text_field :title, placeholder: "タイトル" %>
      <%= f.file_field :files, multiple: true %>
      ※2つ目にPDFデータを選択してください
      <%= f.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="contents row">
  <% @subjects.each_slice(3) do |row| %>
    <div class="row">
      <% row.each do |subject| %>
        <div class="col">
          <%= image_tag subject.image.variant(resize: '300x300'), class: 'subject-image' if subject.image.attached? %>
          <%= link_to subject_path(subject) do %>
            <div class="subject-name">
              <p><%= subject.subject_name %></p>
            </div>
              <% if current_user && subject.user_id == current_user.id %>
                <%= link_to "削除", subject_path(subject), data: { turbo_method: :delete }, class: "delete-button2", 'data-confirm': '本当に削除していいですか？(投稿されたデータも全て削除されます)' %>
              <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>